[development]
address = "0.0.0.0"
port = 7123
keep_alive = 5
log = "off"
limits = { forms = 32768 }


[production]
address = "0.0.0.0"
port = 7123
keep_alive = 5
log = "off"
limits = { forms = 32768 }