name: Build, bump tag version and release

on:
  push:
    branches:
      - master

jobs:
  publish:
    if: false # always skip job for now
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: factorio-bot-backend-linux
            asset_name: factorio-bot-backend-linux
          - os: windows-latest
            artifact_name: factorio-bot-backend.exe
            asset_name: factorio-bot-backend.exe
          - os: macos-latest
            artifact_name: factorio-bot-backend-macos
            asset_name: factorio-bot-backend-macos

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --release --locked
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
